### PR TITLE
hotspot & name convention update

### PR DESCRIPTION
**Pull request by DannyS03**
https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308

### CODE REVIEW

**Comment by NimG98** [comment]
change [hotspot=Albumns file=0]`albums` in README.adoc is spelled wrong (Albumns -> Albums)

**Comment by NimG98** [comment]
Yasson hotspot for dependency in pom.xml isn't formatted correctly: `<!-- Yasson[] -->`
It needs `tag::` and `end::`

**Comment by gkwan-ibm** [comment]
For the paragraph,
"Open Liberty’s JSON-B feature on Maven Central includes the JSON-B provider through transitive dependencies. The `JSON-B provider` has been added as a dependency in your pom.xml"
Update the `JSON-B provider` to "`jsonb-1.0` feature"

**Comment by DannyS03** [comment]
Looks good on qa.

**Pull request merged**
