### PR TITLE
content update 

### PR DESCRIPTION
**Pull request by salmad3**
Addresses the following issues:
- https://github.com/OpenLiberty/guide-rest-client-java/issues/13
- https://github.com/OpenLiberty/guide-rest-client-java/issues/61
- https://github.com/OpenLiberty/guide-rest-client-java/issues/27

### CODE REVIEW

**Review by TiagoF99 — APPROVED** [review]
Looks like all changes requested have been addressed

**Review by gkwan-ibm — APPROVED** [review]
@DannyS03 
- [x] It weird to rename "Introducing JSON-B and JSON-P" to "Introducing Java&trade APIs". 
- [x] JSON-B may be a Liberty feature. Is it really a Java&trade API? It is not clear enough just change "feature" to "Java&trade API"
- [ ] I am not clear your changes are addressing which point of the issues. It is hard for me to just your changes are good or not.
- did you try how try your change in lgdev?

**Comment by AustinSeto** [comment]
Removed use of term "Java&trade APIs" and changed term and checked on lgdev site.

**Comment by gkwan-ibm** [comment]
close
- not sure what to fix

**Pull request closed without merging**
