### PR TITLE
Add try what'll build.

### PR DESCRIPTION
**Pull request by jj-zhang**

### CODE REVIEW

**Comment by NimG98** [comment]
When i visit the url `http://localhost:9080/artists/total/dj`, it should display the number of albums for that artists (which is 0 for dj), but it displays an error page.

I'll make an issue for this, but can you fix it in this PR too?

**Comment by MaiHameed** [comment]
> URL is messed up here:
> 
> image
> 
> it should be like:
> 
> image

This issue still shows up on the lgdev site

**Comment by MaiHameed** [comment]
Issue also exists in the `Running the application` section:

**Comment by jj-zhang** [comment]
@MaiHameed The defect is fixed, ready for your review.

**Comment by DannyS03** [comment]
- tested/verified on `qa`. 
- LGTM.

**Pull request merged**
